### ISSUE TITLE
progress bar not showing on mobile browser

### ISSUE THREAD

**Issue by rvnobre** [stefandobre/Progress-Bar#2] opened 2019-10-29 19:00 UTC
Hi, first congrats on the plugin.

Trying to use ona android mobile browser and progress bar is blank. Desktop browser works fine (eg: Safari). any idea ? Thanks

**Comment by rvnobre** [comment] 2019-10-29 19:02
![image](https://user-images.githubusercontent.com/1025353/67800082-70a4cc00-fa65-11e9-8010-74d4b3a12c4b.png)

**Comment by rvnobre** [comment] 2019-10-29 19:05
on desktop works fine
![image](https://user-images.githubusercontent.com/1025353/67800383-ec9f1400-fa65-11e9-8b7d-688b48677b83.png)

**Comment by stefandobre** [comment] 2019-10-29 19:30
Hi
Which android browser did you test it on?

**Comment by rvnobre** [comment] 2019-10-29 19:33
Stefan, on chrome, but if you try the desktop Safari and simulate the mobile disappear as well (on webdeveloper and mobile icon selected)

**Comment by rvnobre** [comment] 2019-10-29 19:33
Responsive design mode selected on safari

**Comment by stefandobre** [comment] 2019-10-29 21:39
I tried on chrome on android, and responsive mode on safari, they show as intended.
But then again, I tested with my own implementation on https://apex.oracle.com/pls/apex/f?p=60314:20
Could you also check this page in your environment? Are the progress bars showing?

**Comment by stefandobre** [comment] 2021-09-25 11:24
Closing due to lack of info.

**Closed as completed by stefandobre** 2021-09-25 11:24 UTC
